version: 2.1

parameters:
  ECS_DEPLOY:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/python:2.7.16

    steps:
      - checkout
      - run: uname -a

      - when:
          condition:
            or:
              - equal: [ main, << pipeline.git.branch >> ]
              - equal: [ true, << pipeline.parameters.ECS_DEPLOY >> ]
            steps:
              - run:
                  name: branch
                  command: git rev-parse --abbrev-ref HEAD
              - run:
                  name: ECS_DEPLOY
                  command: echo << pipeline.parameters.ECS_DEPLOY >>
