version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:2.7.16

    steps:
      - checkout
      - run: uname -a

      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps:
            - run:
                name: running stuff for main branch
                command: git rev-parse --abbrev-ref HEAD
